"agile": agile
'agile.issue': issue
'agile.release': release
'agile.backlog':  backlog
'agile.scrumboard':  scrumboard
'agile.component': component
'agile.reporthost': reportHost
'agile.reportboard': reportboard
'agile.projectsetting': projectSetting
'agile.fastsearch': fastSearch
'agile.issuelink': issueLink
'agile.userStoryMap': userStoryMap
'agile.iterationBoard': iterationBoard
'agile.messageNotification': messageNotification
