"agile": agile
'agile.issue': issue
'agile.release': release
'agile.backlog':  backlog
'agile.scrumboard':  scrumboard
'agile.component': component
'agile.burndownchart': burndownchart
'agile.report': report