"agile": agile
'agile.issue': issue
'agile.release': release
'agile.backlog':  backlog
'agile.scrumboard':  scrumboard
'agile.component': component
'agile.reporthost': Agile Report
'agile.reportboard': Report
'agile.projectsetting': projectSetting
'agile.fastsearch': fastSearch
'agile.issuelink': issueLink
'agile.userStoryMap': storyMap
'agile.iterationBoard': iterationBoard
'agile.messageNotification': notificationSetting

"rentsetting": "Organization Settings"
"rentsetting.workCalendar": "Work Calendar"

"platform-reports": "Reports"
"platform-reports.reportboard": "Agile Report"
