"agile": agile
'agile.issue': issue
'agile.release': release
'agile.backlog':  backlog
'agile.scrumboard':  scrumboard
'agile.component': component
'agile.reporthost': reportHost
'agile.projectSetting': projectSetting
'fastSearch': fastSearch
'issueLink': issueLink
'status': status