"agile": 敏捷管理
'agile.issue': 问题管理
'agile.release': 发布版本
'agile.backlog':  待办事项
'agile.scrumboard':  活跃冲刺
'agile.component': 模块管理
'agile.reporthost': 敏捷报表
'agile.reportboard': 报告总览
'agile.projectsetting': 项目设置
'agile.fastsearch': 快速搜索
'agile.issuelink': 问题链接
'agile.userStoryMap': 故事地图
'agile.iterationBoard': 迭代控制台
'agile.messageNotification': 通知设置

"rentsetting": "组织设置"
"rentsetting.workCalendar": "工作日历"

"platform-reports": "报表"
"platform-reports.reportboard": "敏捷报表"
