"agile": 敏捷管理
'agile.issue': 问题管理
'agile.release': 发布版本
'agile.backlog':  待办事项
'agile.scrumboard':  活跃冲刺
'agile.component': 模块管理
'agile.reporthost': 报告
'agile.projectSetting': 项目设置
'fastSearch': 快速搜索
'issueLink': 问题链接
'status': 状态