"agile":
  icon: agile
  sort: 1
  project:
    - "backlog":
        icon: baseline-list_alt
        Routes: /agile/backlog
        sort: 1
        permission:
          - 'agile-service.sprint.queryByProjectId'
    - "scrumboard":
        icon: directions_run
        Routes: /agile/scrumboard
        sort: 2
        permission:
          - 'agile-service.board.queryByProjectId'
          - 'agile-service.board.queryByOptions'
    - "issue":
        icon: assignment
        Routes: /agile/issue
        sort: 4
        permission:
          - 'agile-service.issue.listIssueWithoutSub'
    - "release":
        icon: publish2
        Routes: /agile/release
        sort: 5
        permission:
          - 'agile-service.product-version.listByProjectId'
    - "component":
        icon: extension
        Routes: /agile/component
        sort: 6
        permission:
          - 'agile-service.issue-component.listByProjectId'
    - "reporthost":
        icon: application_model
        Routes: /agile/reporthost
        sort: 7
        permission:
          - 'agile-service.sprint.queryNameByOptions'
    - "reportboard":
        icon: whatshot
        Routes: /agile/reportboard
        sort: 8
        permission:
          - 'agile-service.sprint.queryNameByOptions'
    - "projectsetting":
        icon: folder_shared
        Routes: /agile/projectSetting
        sort: 9
        permission:
          - 'agile-service.project-info.updateProjectInfo'
    - "fastsearch":
        icon: youtube_searched_for
        Routes: /agile/fastSearch
        sort: 10
        permission:
          - 'agile-service.quick-filter.create'
    - "messageNotification":
        icon: notifications
        Routes: /agile/messageNotification
        sort: 11
        permission:
          - 'agile-service.notice.queryByProjectId'
    - "userStoryMap":
        icon: usermap
        Routes: /agile/usermap
        sort: 3
        permission:
          - 'agile-service.issue.listEpic'

# 组织设置
"rentsetting":
  icon: IAM
  sort: 2
  organization: # 组织层的菜单
    - "workCalendar": # 菜单字段
        icon: date_range  # 菜单图标
        Routes: /agile/workCalendar # 菜单对应路由
        sort: 8 # 菜单的次序
        permission: # 菜单内容具有的权限
          - 'agile-service.issue.listEpic'
