"agile":
  icon: today
  sort: 1
  project: 
    - "backlog":
        icon: baseline-list_alt
        Routes: /agile/backlog
        sort: 1
        permission:
          - 'agile-service.issue.queryIssue'
    - "scrumboard":
        icon: directions_run
        Routes: /agile/scrumboard
        sort: 2
        permission:
          - 'agile-service.issue.queryIssue'
    - "issue":
        icon: assignment
        Routes: /agile/issue
        sort: 3
        permission:
          - 'agile-service.issue.queryIssue'
    - "release":
        icon: publish2
        Routes: /agile/release
        sort: 4
        permission:
          - 'agile-service.issue.queryIssue'
    - "component":
        icon: extension
        Routes: /agile/component
        sort: 5
        permission:
          - 'agile-service.issue.queryIssue'
