"agile":
  icon: today
  sort: 1
  project: 
    # 待办事项
    - "backlog":
        icon: baseline-list_alt
        Routes: /agile/backlog
        sort: 1
        permission:
          - 'agile-service.issue.queryIssue'
    # 活跃冲刺
    - "scrumboard":
        icon: directions_run
        Routes: /agile/scrumboard
        sort: 2
        permission:
          - 'agile-service.issue.queryIssue'
    # 问题管理
    - "issue":
        icon: assignment
        Routes: /agile/issue
        sort: 3
        permission:
          - 'agile-service.issue.queryIssue'
    # 发布版本
    - "release":
        icon: publish2
        Routes: /agile/release
        sort: 4
        permission:
          - 'agile-service.issue.queryIssue'
    # 模块管理
    - "component":
        icon: extension
        Routes: /agile/component
        sort: 5
        permission:
          - 'agile-service.issue.queryIssue'
    # 报告
    - "reporthost":
        icon: application_model
        Routes: /agile/reporthost
        sort: 6
        permission:
          - 'agile-service.issue.queryIssue'
    # 项目设置
    - "projectSetting":
        icon: publish2
        Routes: /agile/projectSetting
        sort: 7
        permission:
          - 'agile-service.issue.queryIssue'
    # 快速搜索
    - "fastSearch":
        icon: baseline-list_alt
        Routes: /agile/fastSearch
        sort: 8
        permission:
          - 'agile-service.issue.queryIssue'
    # 问题链接
    - "issueLink":
        icon: extension
        Routes: /agile/issueLink
        sort: 9
        permission:
          - 'agile-service.issue.queryIssue'
    # 状态
    - "status"
        icon: directions_run
        Routes: /agile/status
        sort: 10
        permission:
          - 'agile-service.issue.queryIssue'
